"""Create Order table

Revision ID: 588258b71630
Revises: 22bb53457aa7
Create Date: 2024-09-24 13:33:16.219944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588258b71630'
down_revision = '22bb53457aa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('order_status', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('eta', sa.DateTime(), nullable=False),
    sa.Column('discrepancies', sa.String(length=255), nullable=True),
    sa.Column('cutoff_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
