"""Initial migration

Revision ID: 8bd74268a9e3
Revises: 8164dcf1174b
Create Date: 2024-10-09 11:36:41.686344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd74268a9e3'
down_revision = '8164dcf1174b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completed_outgoing_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('delivery_comment', sa.String(length=255), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=False),
    sa.Column('operative_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operative_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_order_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('changes', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['daily_order_id'], ['daily_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(length=100), nullable=True))
        batch_op.drop_column('comapny')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comapny', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('company')

    op.drop_table('daily_order_update')
    op.drop_table('completed_outgoing_order')
    # ### end Alembic commands ###
